config/routes.rb
Rails.application.routes.draw do
  root to: "jobs#premium"
  resources :jobs do
    post "comments", to: "comments#create"
  end

  get 'hello/world'

  delete 'comments/:id', to: "comments#destroy", as: :comment

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :job
  validates :name, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :comments
  scope :most_recent, -> { order(created_at: :desc) }
#   scope :most_recent, order("created_at DESC")
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @job = Job.find(params[:job_id])
    @comment = @job.comments.build(comment_params)
    if @comment.save
      flash[:notice] = "Comentario salvo com sucesso" 
    else
      flash[:alert] = "Houve um erro ao salvar."
    end
    redirect_back_or_to @job
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back_or_to @comment.job, notice: "Comentario apagado com sucesso."
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  attr_accessor :name

  def world
    @name = "Pedro"
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.most_recent.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def premium
    @jobs = Job.where(premium: true).most_recent.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :premium)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/comments/_comment.html.erb
<li class="list-group-item">
  <p>
    <%= comment.name %>
  </p>

  <%= simple_format comment.body %>

  Sent <%= time_ago_in_words comment.created_at %>

  <%= link_to "Delete", 
  comment_path(comment), 
  data: {turbo_method: :delete, turbo_confirm: 'Você quer deletar?'},
  class: "btn btn-outline-danger"
  %>
</li>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new] do |form| %>
  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class:"form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Send" %>
  </div>
<% end %>

app/views/hello/world.html.erb
<h1>Hello World</h1>
<p>
  Olá, <%= @name%>
</p>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>


  <div class="form-check">
    <%= form.label :premium, class: "form-check-label" %>
    <%= form.check_box :premium, class: "form-check-input" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <%= form.submit "save", :class => 'btn btn-outline-primary' %>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>" style="margin: 1%">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
        <%= job.title %>
      </h5>
      <p class="card-text">
        <%= job.description %>
      </p>
      <p>
        <%= check_box("tag", job.id, {checked: job.premium, class: "form-check-input", disabled: true}) %>
        Premium 
      </p>
      <p>
        <%= pluralize(job.comments.size, " comment") %>
      <p/>
      <%= link_to 'Show', job, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/jobs/_jobs.html.erb
<div id="jobs">
  <% @jobs.each do |job| %>
    <%= render job %>
    <p>
      <%= link_to "Show this job", job %>
    </p>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>

<%= render @jobs %>

<%= link_to "New job", new_job_path %>
<br>
<%= link_to "Hello World", hello_world_path %>
<br>
<%= link_to "Jobs Premium", root_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/premium.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs Premium</h1>

<%= render @jobs %>

<%= link_to "Jobs", jobs_path %>

<br>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <p><%= pluralize(@job.comments.size, " comment") %> </>
  <%= button_to "Destroy this job", @job, method: :delete, class: "btn btn-outline-danger" %>
</div>

<div style="margin: 1% 0%">
<!-- Button trigger modal -->
  <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add comment
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">New comment</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "/comments/form" %>
      </div>
    </div>
  </div>
</div>

<ul class="list-group list-group-flush">
  <h6>Comments</h6>
  <%= render @job.comments %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>